module.exports = [
  {
    "title": "Mercury",
    "milesFromSun": "35.98 million",
    "climate": "Since Mercury has hardly any atmosphere, it does not have weather like storms, clouds, winds or rain. Its surface temperature can reach 801 Fahrenheit during the day (because it is so close to the Sun) and can drop to -279 Fahrenheit at night (because there is no atmosphere to trap the daytime heat).",
    "sunRevolution": 87.969,
    "atmosphere": "none",
    "moons": 0,
    "Description": "The smallest planet in our solar system and nearest to the Sun, Mercury is only slightly larger than Earth's Moon.  From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as seven times brighter. Despite its proximity to the Sun, Mercury is not the hottest planet in our solar system – that title belongs to nearby Venus, thanks to its dense atmosphere.",
    "travelTime": 6.5,
    "diameter": "3,031 miles",
    "gravity": 0.38,
    "averageTemp": "-297 to 800",
    "dayLength": "59 Earth days",
    "image": "https://solarsystem.nasa.gov/system/stellar_items/image_files/2_feature_1600x900_mercury.jpg",
    "namesake": "Messenger of the Roman gods",
    "discovery": "Known to the ancients and visible to the naked eye",
    "successfulMissions": "Mariner 10, MESSENGER",
    "image2": "https://cosmos-magazine.imgix.net/file/spina/photo/3385/080316_mercury_1.png?ixlib=rails-1.1.0&h=820&w=1061",
    "cutout": "https://vignette.wikia.nocookie.net/thesolarsystem6361/images/5/50/Mercury_spacepedia.png/revision/latest?cb=20180301162112"
  },
  {
    "title": "Venus",
    "milesFromSun": "67.24 million",
    "climate": "The climate on Venus is widely known to be unpleasant -- at the surface, the planet roasts at more than 800 degrees Fahrenheit under a suffocating blanket of sulfuric acid clouds and a crushing atmosphere more than 90 times the pressure of Earth's. Intrepid future explorers should abandon any hope for better days, however, because it won't change much.",
    "sunRevolution": 224.7,
    "atmosphere": "Carbon dioxide, nitrogen",
    "moons": 0,
    "Description": "Second planet from the Sun and our closest planetary neighbor, Venus is similar in structure and size to Earth, but it is now a very different world. Venus spins slowly in the opposite direction most planets do. Its thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system—with surface temperatures hot enough to melt lead. Glimpses below the clouds reveal volcanoes and deformed mountains.",
    "travelTime": 1.25,
    "diameter": "7,521 miles",
    "gravity": 0.9,
    "averageTemp": 896,
    "dayLength": "243 Earth days",
    "image": "https://solarsystem.nasa.gov/system/stellar_items/image_files/3_feature_1600x900_venus.jpg",
    "namesake": "Roman goddess of love and beauty",
    "discovery": "Known to the ancients and visible to the naked eye",
    "successfulMissions": "Mariner 2, Venera 4, Mariner 5, Venera 5, Venera 6, Venera 8, Mariner 10, Venera 9, Venera 10, Venera 11, Venera 12, Pioneer Venus 1, Pioneer Venus 2, Venera 13, Venera 14, Venera 15, Venera 16, Vega 1, Vega 2, Magellan, Galileo, Cassini, MESSENGER, Venus Express, Akatsuki, IKAROS",
    "image2": "https://vignette.wikia.nocookie.net/earth2308/images/d/dc/Venus.png/revision/latest?cb=20190228190727",
    "cutout": "https://vignette.wikia.nocookie.net/thesolarsystem6361/images/6/6e/Venus_surface_spacepedia.png/revision/latest?cb=20180322151813"
  },
  {
    "title": "Earth",
    "milesFromSun": "92.96 million",
    "climate": "The Earth's climate has changed throughout history. Just in the last 650,000 years there have been seven cycles of glacial advance and retreat, with the abrupt end of the last ice age about 7,000 years ago marking the beginning of the modern climate era — and of human civilization. Most of these climate changes are attributed to very small variations in Earth’s orbit that change the amount of solar energy our planet receives.",
    "sunRevolution": 365.2564,
    "atmosphere": "Nitrogen, oxygen, water vapor, other trace gases",
    "moons": 1,
    "Description": "Our home planet is the third planet from the Sun, and the only place we know of so far that’s inhabited by living things.  While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal.",
    "travelTime": 0,
    "diameter": "7,926 miles",
    "gravity": 1,
    "averageTemp": 57,
    "dayLength": "1 Earth day",
    "image": "https://cms.qz.com/wp-content/uploads/2014/03/globe_west_2400.jpg?quality=75&strip=all&w=1600&h=900&crop=1",
    "namesake": "English/German name which simply means \"the ground\".",
    "discovery": "N/A",
    "successfulMissions": "N/A",
    "image2": "https://wallpaperstream.com/wallpapers/full/universe/Earth-Surface-Wallpaper.jpg",
    "cutout": "https://theplanets.org/wp-content/uploads/2014/09/earth.png"
  },
  {
    "title": "Mars",
    "milesFromSun": "141.6 million",
    "climate": "The atmosphere on Mars is extremely thin. Mars is an extremely cold planet with an average temperature around minus-80 degrees. Temperatures can dip to minus-225 degrees around the poles. Periods of warmth are brief — highs can reach 70 degrees for a brief time around Noon at the equator in the summer.",
    "sunRevolution": 687,
    "atmosphere": "Carbon dioxide, argon, nitrogen, traces of oxygen and water",
    "moons": 2,
    "Description": "The fourth planet from the Sun, Mars is a dusty, cold, desert world with a very thin atmosphere.  This dynamic planet has seasons, polar ice caps and weather and canyons and extinct volacanoes, evidence of an even more active past.  Mars is one of the most explored bodies in our solar system, and it's the only planet where we've sent rovers to roam the alien landscape.",
    "travelTime": 0.58,
    "diameter": "4,222 miles",
    "gravity": 0.38,
    "averageTemp": -81,
    "dayLength": "24 hours & 37 minutes",
    "image": "https://www.jpl.nasa.gov/images/mars/20160421/PIA00407-16.jpg",
    "namesake": "Roman god of war",
    "discovery": "Known to the ancients and visible to the naked eye",
    "successfulMissions": "Mariner 4, Mariner 6, Mariner 7, Mars 2, Mars 3, Mariner 9, Viking 1, Viking 2, Mars Global Surveyor, Mars Pathfinder, Sojourner, Mars Odyssey, Mars Express, Spirit, Opprutunity, Rosetta, Mars Reconnaissance Orbiter, Phoenex, Dawn, Curiosity, Mars Orbiter Mission, MAVEN, ExoMars Trace Gas Orbiter, InSight & MarCO",
    "image2": "https://cdn.mos.cms.futurecdn.net/br4FkqpBujNhxsTfxgtXdE.jpg",
    "cutout": "https://i.dlpng.com/static/png/305213_preview.png"
  },
  {
    "title": "Jupiter",
    "milesFromSun": "483.8 million",
    "climate": "With an average temperature of minus 234 degrees Fahrenheit (minus 145 degrees Celsius), Jupiter is frigid even in its warmest weather. Unlike Earth, whose temperature varies as one moves closer to or farther from the equator, Jupiter's temperature depends more on height above the surface. This is because heat is driven not by the sun but by the interior of the planet.",
    "sunRevolution": "4,332.59",
    "atmosphere": "Molecular hydrogen, helium, traces of ammonia, hydrogen sulfide, water vapor.",
    "moons": 79,
    "Description": "Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system – more than twice as massive as all the other planets combined.  Jupiter's familiar stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiter’s iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years.",
    "travelTime": 6,
    "diameter": "88,846 miles",
    "gravity": 2.64,
    "averageTemp": -202,
    "dayLength": "9 hours & 55 minutes",
    "image": "https://thumbs-prod.si-cdn.com/_MQ5Bn_W8kzbL4mIP8Jv_NDSCMU=/fit-in/1600x0/https://public-media.si-cdn.com/filer/79/c9/79c978d0-ecfa-4e8e-9955-c66ce1b2a35e/pia02873-16.jpg",
    "namesake": "Ruler of the Roman gods",
    "discovery": "Known to the ancients and visible to the naked eye",
    "successfulMissions": "Cassini, Galileo, Voyager1, Voyager2, Pioneer11, Pioneer10",
    "image2": "https://cdn.vox-cdn.com/thumbor/J85lBLditBHKUEguiZh8rPEmWqg=/0x0:3805x1288/1200x675/filters:focal(1599x340:2207x948)/cdn.vox-cdn.com/uploads/chorus_image/image/59799667/pia21974.0.jpg",
    "cutout": "https://www.solarsystemscope.com/spacepedia/images/handbook/renders/jupiter.png"
  },
  {
    "title": "Saturn",
    "milesFromSun": "890.8 million",
    "climate": "With an average temperature of minus 288 degrees Fahrenheit (minus 178 degrees Celsius), Saturn is a pretty cool planet. Although there are some small differences as one travels from the equator to the poles, much of Saturn's temperature variation is horizontal. This is because most of the planet's heat comes from its interior, rather than from the sun.",
    "sunRevolution": "10,759",
    "atmosphere": "Molecular hydrogen, Helium, traces of acetylene, ethane, propane, phosphase, methane.",
    "moons": 62,
    "Description": "Saturn is the sixth planet from the Sun and the second largest planet in our solar system.  Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings—made of chunks of ice and rock—but none are as spectacular or as complicated as Saturn's.  Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium.",
    "travelTime": 7,
    "diameter": "74,900 miles",
    "gravity": 1.16,
    "averageTemp": -202,
    "dayLength": "10 hours & 39 minutes",
    "image": "https://videos.newsweek.com/en/full/2023569/saturn.jpg",
    "namesake": "Roman god of agriculture",
    "discovery": "Known to the ancients and visible to the naked eye",
    "successfulMissions": "Pioneer111, Voyager 1, Voyager 2, Cassini/Huygens",
    "image2": "https://cdn.mos.cms.futurecdn.net/pLmwQQDFY3i4Z4hAjXuDYS-1200-80.jpg",
    "cutout": "https://i1.wp.com/freepngimages.com/wp-content/uploads/2016/04/saturn-transparent-background-planet-1.png?fit=797%2C620"
  },
  {
    "title": "Uranus",
    "milesFromSun": "1.784 billion",
    "climate": "The seventh planet from the sun, Uranus has the coldest atmosphere of any of the planets in the solar system, even though it is not the most distant. Despite the fact that its equator faces away from the sun, the temperature distribution on Uranus is much like other planets, with a warmer equator and cooler poles.",
    "sunRevolution": "30,688.50",
    "atmosphere": "Water vapor, ammonium hydrosulfide, ammonia, hydrogen.",
    "moons": 27,
    "Description": "The seventh planet from the Sun with the third largest diameter in our solar system, Uranus is very cold and windy. The ice giant is surrounded by 13 faint rings and 27 small moons as it rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin on its side, orbiting the Sun like a rolling ball.",
    "travelTime": 8.5,
    "diameter": "31,763 miles",
    "gravity": 1.11,
    "averageTemp": -328,
    "dayLength": "17 hours & 14 minutes",
    "image": "https://solarsystem.nasa.gov/system/stellar_items/image_files/69_feature_1600x900_uranus_new.jpg",
    "namesake": "Personification of heaven in ancient myth",
    "discovery": "1781 by William Hersche",
    "successfulMissions": "Voyager 2",
    "image2": "https://www.kuaf.com/sites/kuaf/files/styles/x_large/public/201907/pri_44829263.jpg",
    "cutout": "https://www.coolaboo.com/wp-content/uploads/2019/03/Uranus.png"
  },
  {
    "title": "Neptune",
    "milesFromSun": "2.793 billion",
    "climate": "Neptune has the wildest and strangest weather in the entire Solar System. It has huge storms with extremely high winds. Its atmosphere has dark spots which come and go, and bright cirrus-like clouds which change rapidly. Neptune has an average temperature of -353 Fahrenheit (-214 Celsius).",
    "sunRevolution": "60,182",
    "atmosphere": "Hydrogen, helium, traces of mathane.",
    "moons": 14,
    "Description": "Dark, cold and whipped by supersonic winds, ice giant Neptune is the eighth and most distant planet in our solar system.  More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye.  Neptune is so far from the Sun that high noon on the big blue planet would seem like dim twilight to us. The warm light we see here on our home planet is roughly 900 times as bright as sunlight on Neptune.",
    "travelTime": 12,
    "diameter": "30,779 miles",
    "gravity": 1.21,
    "averageTemp": -328,
    "dayLength": "16 hours & 7 min",
    "image": "https://solarsystem.nasa.gov/system/stellar_items/image_files/90_feature_1600x900_4.jpg",
    "namesake": "Roman god of water",
    "discovery": 1846,
    "successfulMissions": "Voyager 2",
    "image2": "https://www.nasa.gov/sites/default/files/thumbnails/image/neptune_voyager1.jpg",
    "cutout": "https://theplanets.org/wp-content/uploads/2014/09/neptune.png"
  },
  {
    "title": "Pluto",
    "milesFromSun": "3.67 billion",
    "climate": "Lying 30 to 50 times Earth's distance from the sun, Pluto is one of the coldest large bodies in the solar system. But despite the fact that it lies so far away, its temperature can shift enough over the course of its orbit to significantly impact the planet.  At its warmest, when it is closest to the sun, Pluto can reach temperatures of minus 369 degrees Fahrenheit (minus 223 degrees Celsius). At its coolest, temperatures can fall to minus 387 degrees F (minus 233 C).",
    "sunRevolution": "90,600",
    "atmosphere": "Nitrogen, traces of methane and carbon monoxide.",
    "moons": 5,
    "Description": "Pluto, once considered the ninth and most distant planet from the sun, is now the largest known dwarf planet in the solar system. It is also one of the largest known members of the Kuiper Belt, a shadowy zone beyond the orbit of Neptune thought to be populated by hundreds of thousands of rocky, icy bodies each larger than 62 miles (100 kilometers) across, along with 1 trillion or more comets.",
    "travelTime": 9.5,
    "diameter": "1,473 miles",
    "gravity": 0.083,
    "averageTemp": -378,
    "dayLength": "6 Earth days & 9 hours",
    "image": "https://cdn.cnn.com/cnnnext/dam/assets/150714084003-01-pluto-horizon-0714-super-tease.jpg",
    "namesake": "Roman god of the underworld",
    "discovery": "1930 by Clyde Tombaugh",
    "successfulMissions": "New Horizons",
    "image2": "https://media.daysoftheyear.com/20171223131353/pluto-day.jpg",
    "cutout": "https://www.solarsystemscope.com/spacepedia/images/handbook/renders/pluto.png"
  }
];

